spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 821843855579-1oteo6prb96g5p82jk137gdglg3s717u.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8080
